name: build and test

on: [push]

env:
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "3.1.x"
      - run: dotnet restore src
      - run: dotnet build src
      - run: dotnet test src
